apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-test-1-argo-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/VorapratR/argocd-app-config
    targetRevision: HEAD
    path: app-test-1
  destination: 
    server: https://kubernetes.default.svc
    namespace: app-test-1

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true